// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCounter = "counter"

// Counter mapped from table <counter>
type Counter struct {
	ID         uint64 `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                               // id
	MsgID      uint64 `gorm:"column:msg_id;type:bigint unsigned;not null;uniqueIndex:uniq_counter,priority:2" json:"msg_id"`        // 业务计数场景的消息(业务)id
	CounterKey string `gorm:"column:counter_key;type:varchar(128);not null;uniqueIndex:uniq_counter,priority:1" json:"counter_key"` // 业务计数场景的唯一key
	CounterNum uint32 `gorm:"column:counter_num;type:int unsigned;not null" json:"counter_num"`                                     // 计数器数量
}

// TableName Counter's table name
func (*Counter) TableName() string {
	return TableNameCounter
}
