// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDconfigEnterprise = "dconfig_enterprise"

// DconfigEnterprise mapped from table <dconfig_enterprise>
type DconfigEnterprise struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                           // id
	EnterpriseID int64          `gorm:"column:enterprise_id;type:bigint;not null;uniqueIndex:uk_dconfig,priority:1" json:"enterprise_id"` // enterprise_id
	Namespace    string         `gorm:"column:namespace;type:varchar(64);not null;uniqueIndex:uk_dconfig,priority:2" json:"namespace"`    // 业务命名空间
	Key          string         `gorm:"column:key;type:varchar(64);not null;uniqueIndex:uk_dconfig,priority:3" json:"key"`                // 配置的key，格式模板为xxx.xxx.xxx...
	Content      string         `gorm:"column:content;type:varchar(512);not null" json:"content"`                                         // 配置内容
	Version      int32          `gorm:"column:version;type:int;not null;uniqueIndex:uk_dconfig,priority:4" json:"version"`                // 配置版本
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdateAt     time.Time      `gorm:"column:update_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
}

// TableName DconfigEnterprise's table name
func (*DconfigEnterprise) TableName() string {
	return TableNameDconfigEnterprise
}
