// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDconfig = "dconfig"

// Dconfig mapped from table <dconfig>
type Dconfig struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`                        // id
	Namespace string         `gorm:"column:namespace;type:varchar(64);not null;uniqueIndex:uk_dconfig,priority:1" json:"namespace"` // 业务命名空间
	Key       string         `gorm:"column:key;type:varchar(64);not null;uniqueIndex:uk_dconfig,priority:2" json:"key"`             // 配置的key，格式模板为xxx.xxx.xxx...
	Content   string         `gorm:"column:content;type:varchar(512);not null" json:"content"`                                      // 配置内容
	Version   int32          `gorm:"column:version;type:int;not null;uniqueIndex:uk_dconfig,priority:3" json:"version"`             // 配置版本
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdateAt  time.Time      `gorm:"column:update_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
}

// TableName Dconfig's table name
func (*Dconfig) TableName() string {
	return TableNameDconfig
}
