// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		Counter:           newCounter(db, opts...),
		Dconfig:           newDconfig(db, opts...),
		DconfigEnterprise: newDconfigEnterprise(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Counter           counter
	Dconfig           dconfig
	DconfigEnterprise dconfigEnterprise
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Counter:           q.Counter.clone(db),
		Dconfig:           q.Dconfig.clone(db),
		DconfigEnterprise: q.DconfigEnterprise.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Counter:           q.Counter.replaceDB(db),
		Dconfig:           q.Dconfig.replaceDB(db),
		DconfigEnterprise: q.DconfigEnterprise.replaceDB(db),
	}
}

type queryCtx struct {
	Counter           *counterDo
	Dconfig           *dconfigDo
	DconfigEnterprise *dconfigEnterpriseDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Counter:           q.Counter.WithContext(ctx),
		Dconfig:           q.Dconfig.WithContext(ctx),
		DconfigEnterprise: q.DconfigEnterprise.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
